---
title: "DATA"
output: html_notebook
---
##Packages
```{r}
library(ggplot2)
library(DiagrammeR)
library(questionr)
```




## Data
```{r}
getwd()
#baseline = read.csv(file = "W:/Odélia/srh_retraite/data/inclusion/Baseline20190215.csv", header = TRUE, row.names = NULL, sep = ';')
#suivi_6 = read.csv(file = "W:/Odélia/srh_retraite/data/6_ans/suivi6.csv", header = TRUE, row.names = NULL, sep = ";")
#suivi_4 = read.csv(file = "W:/Odélia/srh_retraite/data/4_ans/suivi4.csv", header = TRUE, row.names = NULL, sep = ";")
```


## Gestions types
```{r}
#activpro
baseline$Adm12a = as.factor(baseline$Adm12a)
baseline$Adm11 = as.factor(baseline$Adm11)
baseline$Adm10 = as.factor(baseline$Adm10)
baseline$Adm12 = as.factor(baseline$Adm12)
baseline$actpro = as.factor(baseline$actpro)
baseline$activpro = as.factor(baseline$activpro)
baseline$sexe = as.factor(baseline$sexe)

#sexe
baseline$age0 = as.numeric(baseline$age0)
baseline$age0Cut = as.factor(baseline$age0Cut)

#self rated health
baseline$Qm73 = as.factor(baseline$Qm73)
baseline$srhBin = as.factor(baseline$srhBin)
baseline$srhNum = as.numeric(baseline$srhNum)

#entourage
baseline$qm2 = as.factor(baseline$qm2)
baseline$entourage = as.factor(baseline$entourage)

#tabac
baseline$Qm16 = as.factor(baseline$Qm16)
baseline$tabac = as.factor(baseline$tabac)

#cardio vascular desease
baseline$Qm35 = as.factor(baseline$Qm35)
baseline$AP_pontage = as.factor(baseline$AP_pontage)
baseline$Qm37 = as.factor(baseline$Qm37)
baseline$Qm38 = as.factor(baseline$Qm38)
baseline$Qm39 = as.factor(baseline$Qm39)
baseline$Qm40 = as.factor(baseline$Qm40)
baseline$Qm41 = as.factor(baseline$Qm41)
baseline$cvd = as.factor(baseline$cvd)
baseline$cvd_score = as.factor(baseline$cvd_score)

#cancer
baseline$Qm67 = as.factor(baseline$Qm67)

#TS
baseline$TS = as.factor(baseline$TS)

baseline$Qm34 = as.factor(baseline$Qm34)
```

## Data intermediaires

```{r}
baselineP = baseline[-(which(baseline$nepp3 %in% na_activpro_id)),]

baselineP1 = baselineP[-(which(baselineP$nepp3 %in% na_srh_id)),]

baselineP2 = baselineP1[-(which(baselineP1$nepp3 %in% outliers_age_id)),]

baselineP3 = baselineP2[-(which(baselineP2$nepp3 %in% na_entourage_id)),]

baselineP4 = baselineP3[-(which(baselineP3$nepp3 %in% na_tabac_id)),]

baselineP5 = baselineP4[-(which(baselineP4$nepp3 %in% na_cvd_id)),]

baselineP6 = baselineP5[-(which(baselineP5$nepp3 %in% na_cancer_id)),]
```

## Gestion des exclus

```{r}
exclus_id = unique(c(na_activpro_id, na_srh_id, outliers_age_id, na_entourage_id, na_tabac_id, na_cvd_id, na_cancer_id))
length(exclus_id)
```


```{r}
exclus = baseline[which(baseline$nepp3 %in% exclus_id),]
dim(exclus)
```
```{r}
#compareGroups(baseline,exclus)
```

