---
title: "Vérification des hypothses"
output: html_notebook
---

## Modele linéaire

```{r}
ggplot(baselineP1, aes (x = baselineP1$srhNum)) + geom_histogram(col = "green", fill = "skyblue") + geom_vline( aes(xintercept = mean(baselineP1$srhNum) ) , col = "blue") +  ggtitle("Distribution de la santé perçue linéarisée dans baselineP1, n = 10 071")
```
```{r}
mean(baselineP1$srhNum)
```


```{r}
e = 0
while (e < 1000){
  randomBL = baselineP1[sample(baselineP1$nepp3,5000),]
  test = shapiro.test(randomBL$srhNum)
  if(test$p.value > 0.05){
    print(test$p.value)
    e = 1000
    }
  else 
    e = e + 1
}
```

```{r}
df3 = as.data.frame(cbind(rbind("I","C","T","R"),
                          rbind(round(mean(baselineP1$srhNum[which(baselineP1$activpro == "I")]),2)  ,
                                round(mean(baselineP1$srhNum[which(baselineP1$activpro == "C")]),2),
                                round(mean(baselineP1$srhNum[which(baselineP1$activpro == "T")]),2),
                                round(mean(baselineP1$srhNum[which(baselineP1$activpro == "R")]),2))))
df3
```
```{r}
ggplot(df3, aes(df3[,1], df3[,2])) + geom_point()
```


```{r}
ggplot(baselineP1, aes(baselineP1$age0, baselineP1$srhNum, col = baselineP1$activpro )) + geom_point()
```

```{r}
baseline$activpro = as.factor(baseline$activpro)
for(z in 1:(dim(baseline)[1])){
  if(is.na(baseline$activpro[z]))
    baseline$activproBin[z] = NA
  else if (baseline$activpro[z] == "R")
    baseline$activproBin[z] = "R"
  else 
    baseline$activproBin[z] = "NON R"
}

baseline$activproBin = as.factor(baseline$activproBin)
```
```{r}
summary(baseline$activpro)
summary(baseline$activproBin)
```


```{r}
ggplot(baselineP1, aes(baselineP1$age0, baselineP1$srhNum, col = baselineP1$activproBin )) + geom_point()
```

